## Basic data filtering and columns normalization

In [1]:
import pandas as pd
import re
import warnings
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
from datetime import datetime, timedelta
# Since our dataset is very big and with many columns we activate this option to show all columns
pd.set_option('display.max_columns', 100)

warnings.filterwarnings("ignore")
dataset = pd.read_csv('C:\\Users\\VideoMachine\\IH-labs\\Fire-Project\\NEW_DATA\\ICNF_2013_2022_full.csv')

In [2]:
dataset.head()

,DISTRITO,TIPO,ANO,AREAPOV,AREAMATO,AREAAGRIC,AREATOTAL,REACENDIMENTOS,QUEIMADA,FALSOALARME,FOGACHO,INCENDIO,AGRICOLA,NCCO,NOMECCO,DATAALERTA,HORAALERTA,LOCAL,CONCELHO,FREGUESIA,FONTEALERTA,INE,X,Y,DIA,MES,HORA,OPERADOR,PERIMETRO,APS,CAUSA,TIPOCAUSA,DHINICIO,DHFIM,DURACAO,HAHORA,DATAEXTINCAO,HORAEXTINCAO,DATA1INTERVENCAO,HORA1INTERVENCAO,QUEIMA,LAT,LON,CAUSAFAMILIA,TEMPERATURA,HUMIDADERELATIVA,VENTOINTENSIDADE,VENTOINTENSIDADE_VETOR,VENTODIRECAO_VETOR,PRECEPITACAO,FFMC,DMC,DC,ISI,BUI,FWI,DSR,THC,MODFARSITE,ALTITUDEMEDIA,DECLIVEMEDIO,HORASEXPOSICAOMEDIA,DENDIDADERV,COSN5VARIEDADE,AREAMANCHAMODFARSITE,AREASFICHEIROS_GNR,AREASFICHEIROS_GTF,FICHEIROIMAGEM_GNR,AREASFICHEIROSHP_GTF,AREASFICHEIROSHPXML_GTF,AREASFICHEIRODBF_GTF,AREASFICHEIROPRJ_GTF,AREASFICHEIROSBN_GTF,AREASFICHEIROSBX_GTF,AREASFICHEIROSHX_GTF,AREASFICHEIROZIP_SAA,index
0,Coimbra,Florestal,2013,0.0,0.001,0.0,0.001,0,0,0,1,0,0,2013060000295,6,03-01-2013,17:54,CUNHEDO,Penacova,Oliveira do Mondego,Populares,61305,192399,373499,3,1,17,sigo,NaN,NaN,449.0,Intencional,03-01-2013 17:54:00,03-01-2013 18:29:00,35.0,0.001714,03-01-2013,18:29,03-01-2013,18:10,0,40.330172,-8.222549,Incendiarismo - Imputáveis,15.3,54.0,14.0,-999.0,-999.0,0.0,76.300003,2.2,35.200001,1.7,3.8,0.7,0.01,26.773500,NaN,99.8913,17.5053,NaN,120.767,22.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Coimbra,Florestal,2013,0.0,0.001,0.0,0.001,0,0,0,1,0,0,2013060000445,6,04-01-2013,23:56,Comareira,Góis,Góis,Populares,60604,198300,351000,4,1,23,sigo,NaN,NaN,14.0,Negligente,04-01-2013 23:56:00,05-01-2013 01:40:00,104.0,0.000577,05-01-2013,01:40,05-01-2013,00:15,0,40.127576,-8.153059,Uso do fogo - Fogueiras,14.6,41.0,10.0,-999.0,-999.0,0.0,85.400002,2.9,47.400002,3.7,5.1,2.6,0.15,15.847600,NaN,597.4790,49.9571,NaN,183.455,21.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Coimbra,Florestal,2013,0.0,0.050,0.0,0.050,0,0,0,1,0,0,2013060000377,6,04-01-2013,13:09,Chãs de Égua,Arganil,Piódão,Populares,60111,228799,363099,4,1,13,sigo,NaN,NaN,124.0,Negligente,04-01-2013 13:09:00,04-01-2013 14:30:00,81.0,0.037037,04-01-2013,14:30,04-01-2013,13:45,0,40.236057,-7.794691,Queimas amontoados de sobrantes florestais ou ...,9.6,51.0,28.0,-999.0,-999.0,0.0,81.099998,1.7,25.000000,5.3,3.0,3.2,0.21,20.834101,227.0,748.7660,50.4426,NaN,224.046,11.95,10.8147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Leiria,Florestal,2013,0.1,0.100,0.0,0.200,0,0,0,1,0,0,2013100000560,10,04-01-2013,13:13,Sobreiro,Pedrógão Grande,Pedrógão Grande,Outros,101302,197499,325299,4,1,13,2020419,NaN,NaN,124.0,Negligente,04-01-2013 13:13:00,04-01-2013 13:53:00,40.0,0.300000,04-01-2013,13:53,04-01-2013,13:27,0,39.896117,-8.162342,Queimas amontoados de sobrantes florestais ou ...,9.6,51.0,28.0,-999.0,-999.0,0.0,81.099998,1.7,25.000000,5.3,3.0,3.2,0.21,20.834101,NaN,343.0810,10.0806,NaN,138.011,18.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Leiria,Agrícola,2013,0.0,0.000,6.5,6.500,0,0,0,0,0,1,2013100000546,10,04-01-2013,12:00,PNSAC - ALVADOS,Porto de Mós,Alvados,Populares,101603,145400,287000,4,1,12,2020419,NaN,SERRAS DE AIRE E CANDEEIROS,129.0,Negligente,04-01-2013 12:00:00,04-01-2013 15:08:00,188.0,2.074468,04-01-2013,15:08,04-01-2013,12:10,0,39.549428,-8.768329,Queimadas de sobrantes florestais ou agrícolas,14.9,42.0,14.0,-999.0,-999.0,0.0,85.800003,4.0,40.200001,4.8,6.5,4.1,0.33,15.398800,NaN,264.8890,11.7616,NaN,261.708,15.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

After looking into the columns I can identify a lot of them that are reserved to store optional data and files, we are droping them all together and work from there

In [3]:
#columns to maintain in the dataset
columns_data = ['LAT', 'LON','ANO','TIPO','DISTRITO','CONCELHO','FREGUESIA','DHINICIO','DHFIM','DURACAO',
            'AREAPOV','AREAMATO','AREAAGRIC','AREATOTAL','REACENDIMENTOS', 'HAHORA',  
            'QUEIMADA','FALSOALARME','FOGACHO','INCENDIO','AGRICOLA','TIPOCAUSA', 'HUMIDADERELATIVA','VENTOINTENSIDADE','PRECEPITACAO','FFMC','DMC','DC','ISI','FWI','THC','ALTITUDEMEDIA','DECLIVEMEDIO','DENDIDADERV','COSN5VARIEDADE']  

dataset = dataset[columns_data]

In [4]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
LAT,143131.0,40.478801,1.214036,0.000000,39.485910,41.033043,41.353437,65.243330
LON,143131.0,-8.283952,0.577236,-51.853745,-8.605960,-8.357085,-7.967908,-0.000000
ANO,143131.0,2016.745932,2.776396,2013.000000,2015.000000,2017.000000,2019.000000,2022.000000
DURACAO,142748.0,85.149172,369.995006,-5.000000,27.000000,45.000000,80.000000,49359.000000
AREAPOV,143131.0,4.566280,224.221517,0.000000,0.000000,0.000000,0.000000,47215.433221
AREAMATO,143131.0,3.879583,94.535103,0.000000,0.000000,0.010000,0.129700,13178.860000
AREAAGRIC,143131.0,0.660495,28.682286,0.000000,0.000000,0.000000,0.000000,5493.424200
AREATOTAL,143131.0,9.106358,305.132385,0.000000,0.010000,0.055000,0.500000,53618.811555
REACENDIMENTOS,143131.0,0.069789,0.254792,0.000000,0.000000,0.000000,0.000000,1.000000
HAHORA,142806.0,1.074578,21.208450,0.000000,0.018367,0.088889,0.454545,6902.792308
QUEIMADA,143131.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
FALSOALARME,143131.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
FOGACHO,143131.0,0.652004,0.476336,0.000000,0.000000,1.000000,1.000000,1.000000
INCENDIO,143131.0,0.155857,0.362721,0.000000,0.000000,0.000000,0.000000,1.000000
AGRICOLA,143131.0,0.192139,0.393983,0.000000,0.000000,0.000000,0.000000,1.000000
HUMIDADERELATIVA,123225.0,44.730346,17.460084,0.000000,31.000000,43.000000,56.000000,100.499344
VENTOINTENSIDADE,123200.0,10.163521,6.368834,0.000000,5.723747,9.000000,14.000000,90.000000
PRECEPITACAO,123225.0,0.124679,1.349850,-0.035156,0.000000,0.000000,0.000000,108.000000
FFMC,141610.0,89.223610,71.696991,-80.000000,86.900002,89.759953,92.500000,10071.305664
DMC,141639.0,114.474760,96.841482,-80.000000,37.299999,95.900002,159.000000,1590.033081
DC,141639.0,498.490394,311.520045,-80.000000,228.899994,517.299988,726.970032,6822.709961
ISI,141610.0,7.735870,5.296050,-80.000000,4.600000,7.034608,10.100000,192.699997
FWI,141639.0,25.838629,64.961184,-80.000000,13.000000,25.700001,36.299999,20150.089844
THC,93155.0,12.310276,11.160860,0.000000,8.027330,10.830800,13.847000,249.869003
ALTITUDEMEDIA,143078.0,273.949513,242.165884,-63.792500,86.392500,201.484000,399.721000,1813.540000
DECLIVEMEDIO,143078.0,13.943407,9.434166,0.054086,6.678890,12.007700,19.221600,65.750600
DENDIDADERV,143106.0,344.599511,291.106282,0.000000,149.514000,255.892000,422.554000,2027.110000
COSN5VARIEDADE,143108.0,17.875832,4.871232,1.000000,14.710000,17.820000,21.040000,39.880000

In [5]:
dataset.dtypes

LAT                 float64
LON                 float64
ANO                   int64
TIPO                 object
DISTRITO             object
CONCELHO             object
FREGUESIA            object
DHINICIO             object
DHFIM                object
DURACAO             float64
AREAPOV             float64
AREAMATO            float64
AREAAGRIC           float64
AREATOTAL           float64
REACENDIMENTOS        int64
HAHORA              float64
QUEIMADA              int64
FALSOALARME           int64
FOGACHO               int64
INCENDIO              int64
AGRICOLA              int64
TIPOCAUSA            object
HUMIDADERELATIVA    float64
VENTOINTENSIDADE    float64
PRECEPITACAO        float64
FFMC                float64
DMC                 float64
DC                  float64
ISI                 float64
FWI                 float64
THC                 float64
ALTITUDEMEDIA       float64
DECLIVEMEDIO        float64
DENDIDADERV         float64
COSN5VARIEDADE      float64
dtype: object

### Assigning the correct date/time types to data columns

In [ ]:
dataset['DHINICIO'] = pd.to_datetime(dataset['DHINICIO'])
dataset['DHFIM'] = pd.to_datetime(dataset['DHFIM'])

We can see from the describe that we have huge problems here.

Columns: DURACAO, HAHORA and the areas have massive ranges and in some cases just invalid ones like the DURACAO columns (Duration of the fire)

Lets do some boxplots to find what's what.

In [ ]:
for i in ['DURACAO','HAHORA', 'AREAPOV', 'AREAMATO', 'AREAAGRIC', 'AREATOTAL']:
    print(i)
    plt.boxplot(dataset[i])
    plt.show()

We know that ha burned by hour (HAHORA) is duration(DURACAO)/total area burned (AREATOTAL). So first of all lets check for nan's, as this columns have to possibly be discarded

In [ ]:
# No nan's here
dataset['AREATOTAL'].isna().sum()

Let's recompute the total area just to be sure

In [ ]:
dataset['AREATOTAL'] = dataset['AREAPOV']+dataset['AREAMATO']+dataset['AREAAGRIC']
dataset['AREATOTAL'].describe()

# All good here

Let's check if we have nan durations and begin and end nan dates

In [ ]:
display(dataset['DURACAO'].isna().sum())
display(dataset['DHFIM'].isna().sum())
display(dataset['DHINICIO'].isna().sum())

We have precisely the same number of duration and end date nan's lets check whats happening

In [ ]:
dataset[dataset['DURACAO'].isna()]

I have noticed that some of the records have a ratio per hour of burnt area, so from there we can calculate our duration. as shown bellow.

In [ ]:
dataset['DURACAO'] = np.where(dataset['DURACAO'].isna() & ~dataset['HAHORA'].isna(), dataset['AREATOTAL']/dataset['HAHORA'] ,dataset['DURACAO'])

In [ ]:
display(dataset['DURACAO'].isna().sum())

We addressed some of the rows, but unfortunatly for our further analysis we cant use the columns that we cant calculate duration, we have to drop them.

In [ ]:
dataset = dataset[~dataset['DURACAO'].isna()]

In [ ]:
dataset['DURACAO'].describe()

We have to recalculate all durations and if we can't make sense of them, we have to drop the meaningless columns.

In [ ]:
dataset['DURACAO'] = (dataset['DHFIM'] - dataset['DHINICIO']).dt.total_seconds() / 60 / 60
dataset['DURACAO'].isna().sum()

We have 57 invalid durations wich means we have 57 invalid final dates. Let's check.

In [ ]:
dataset[dataset['DURACAO'].isna()]

Analysing the rows, they all have a ratio of burnt ground vs total area burned and a total area burned so we calculate this ones.

In [ ]:
dataset['DURACAO'] = dataset['DURACAO'].fillna(dataset['AREATOTAL']/dataset['HAHORA'])

In [ ]:
dataset['DURACAO'].describe().T

In [ ]:
dataset[dataset['DURACAO']<0]

Again a problem with negative dates, We are going to calculate again with operation dividing the ratio by the total area burnt

In [ ]:
dataset['DURACAO'] = np.where(dataset['DURACAO']<0, dataset['AREATOTAL']/dataset['HAHORA'], dataset['DURACAO'])

In [ ]:
dataset['AREATOTAL'].describe()

We just have to fill the final dates with the start dates + hours

In [105]:
dataset['DHFIM'] = dataset['DHINICIO'] + pd.to_timedelta(dataset['DURACAO'], unit = 'h')

In [106]:
dataset.head()

,LAT,LON,ANO,TIPO,DISTRITO,CONCELHO,FREGUESIA,DHINICIO,DHFIM,DURACAO,AREAPOV,AREAMATO,AREAAGRIC,AREATOTAL,REACENDIMENTOS,HAHORA,QUEIMADA,FALSOALARME,FOGACHO,INCENDIO,AGRICOLA,TIPOCAUSA,HUMIDADERELATIVA,VENTOINTENSIDADE,PRECEPITACAO,FFMC,DMC,DC,ISI,FWI,THC,ALTITUDEMEDIA,DECLIVEMEDIO,DENDIDADERV,COSN5VARIEDADE
0,40.330172,-8.222549,2013,Florestal,Coimbra,Penacova,Oliveira do Mondego,2013-03-01 17:54:00,2013-03-01 18:28:59.999998800,0.583333,0.0,0.001,0.0,0.001,0,0.001714,0,0,1,0,0,Intencional,54.0,14.0,0.0,76.300003,2.2,35.200001,1.7,0.7,26.773500,99.8913,17.5053,120.767,22.49
1,40.127576,-8.153059,2013,Florestal,Coimbra,Góis,Góis,2013-04-01 23:56:00,2013-05-01 01:39:59.999998800,697.733333,0.0,0.001,0.0,0.001,0,0.000577,0,0,1,0,0,Negligente,41.0,10.0,0.0,85.400002,2.9,47.400002,3.7,2.6,15.847600,597.4790,49.9571,183.455,21.73
2,40.236057,-7.794691,2013,Florestal,Coimbra,Arganil,Piódão,2013-04-01 13:09:00,2013-04-01 14:30:00.000000000,1.350000,0.0,0.050,0.0,0.050,0,0.037037,0,0,1,0,0,Negligente,51.0,28.0,0.0,81.099998,1.7,25.000000,5.3,3.2,20.834101,748.7660,50.4426,224.046,11.95
3,39.896117,-8.162342,2013,Florestal,Leiria,Pedrógão Grande,Pedrógão Grande,2013-04-01 13:13:00,2013-04-01 13:53:00.000001200,0.666667,0.1,0.100,0.0,0.200,0,0.300000,0,0,1,0,0,Negligente,51.0,28.0,0.0,81.099998,1.7,25.000000,5.3,3.2,20.834101,343.0810,10.0806,138.011,18.89
4,39.549428,-8.768329,2013,Agrícola,Leiria,Porto de Mós,Alvados,2013-04-01 12:00:00,2013-04-01 15:07:59.999998800,3.133333,0.0,0.000,6.5,6.500,0,2.074468,0,0,0,0,1,Negligente,42.0,14.0,0.0,85.800003,4.0,40.200001,4.8,4.1,15.398800,264.8890,11.7616,261.708,15.32

We still have 5 nan duration and end dates that are nan, we are going to drop them.

In [107]:
dataset[dataset['DURACAO'].isna()]

,LAT,LON,ANO,TIPO,DISTRITO,CONCELHO,FREGUESIA,DHINICIO,DHFIM,DURACAO,AREAPOV,AREAMATO,AREAAGRIC,AREATOTAL,REACENDIMENTOS,HAHORA,QUEIMADA,FALSOALARME,FOGACHO,INCENDIO,AGRICOLA,TIPOCAUSA,HUMIDADERELATIVA,VENTOINTENSIDADE,PRECEPITACAO,FFMC,DMC,DC,ISI,FWI,THC,ALTITUDEMEDIA,DECLIVEMEDIO,DENDIDADERV,COSN5VARIEDADE
113241,39.180236,-9.079732,2019,Florestal,Lisboa,Cadaval,Vilar,2019-12-09 17:37:00,NaT,NaN,0.0,0.0,0.0,0.0,0,0.0,0,0,1,0,0,NaN,31.427505,20.23826,0.0,94.037186,170.632721,1057.079468,19.155760,58.123363,NaN,385.0770,39.8005,202.590,15.72
133115,40.637990,-8.347085,2022,Florestal,Aveiro,Águeda,Préstimo,2022-12-07 13:55:00,NaT,NaN,0.0,0.0,0.0,0.0,0,0.0,0,0,1,0,0,NaN,NaN,NaN,NaN,95.800003,67.199997,316.600006,14.820000,38.389999,NaN,83.4362,14.6760,446.113,21.26
136663,39.746180,-8.442470,2022,Florestal,Leiria,Alvaiázere,Pelmá,2022-12-07 16:11:00,NaT,NaN,0.0,0.0,0.0,0.0,0,0.0,0,0,1,0,0,NaN,NaN,NaN,NaN,98.199997,112.599998,580.200012,34.770000,79.769997,NaN,134.8490,18.7312,218.640,23.08
136664,39.887220,-8.479300,2022,Florestal,Leiria,Pombal,Abiul,2022-12-07 16:24:00,NaT,NaN,0.0,0.0,0.0,0.0,0,0.0,0,0,1,0,0,NaN,NaN,NaN,NaN,97.599998,103.500000,512.700012,27.639999,67.800003,NaN,194.8370,11.0305,221.195,23.45
136665,39.903500,-8.498300,2022,Florestal,Leiria,Pombal,Abiul,2022-12-07 16:39:00,NaT,NaN,0.0,0.0,0.0,0.0,0,0.0,0,0,1,0,0,NaN,NaN,NaN,NaN,97.599998,103.500000,512.700012,27.639999,67.800003,NaN,250.9660,11.8323,186.096,31.60

In [113]:
final_dataset = dataset[~dataset['DURACAO'].isna()]

#### Renaming columns, I will translate all columns now to english, and lowercase them

In [114]:
final_dataset.columns

Index(['LAT', 'LON', 'ANO', 'TIPO', 'DISTRITO', 'CONCELHO', 'FREGUESIA',
       'DHINICIO', 'DHFIM', 'DURACAO', 'AREAPOV', 'AREAMATO', 'AREAAGRIC',
       'AREATOTAL', 'REACENDIMENTOS', 'HAHORA', 'QUEIMADA', 'FALSOALARME',
       'FOGACHO', 'INCENDIO', 'AGRICOLA', 'TIPOCAUSA', 'HUMIDADERELATIVA',
       'VENTOINTENSIDADE', 'PRECEPITACAO', 'FFMC', 'DMC', 'DC', 'ISI', 'FWI',
       'THC', 'ALTITUDEMEDIA', 'DECLIVEMEDIO', 'DENDIDADERV',
       'COSN5VARIEDADE'],
      dtype='object')

In [115]:
final_dataset.columns = ['lat', 'lon','year','type','district','county','parish','alert_date','extinction_date','duration',
    'area_populated','area_bush','area_agricultural','area_total','reignition', 'hour_ha', 'burned','false_alarm','spark',
    'fire','agricultural','type_cause', 'relative_humidity','wind_intensity', 'precipitation', 'ffmc', 'dmc', 'dc', 'isi', 
    'fwi','thc', 'avg_altitude', 'avg_inclination', 'rvdendity','cosn5variety']

In [116]:
final_dataset.head()

,lat,lon,year,type,district,county,parish,alert_date,extinction_date,duration,area_populated,area_bush,area_agricultural,area_total,reignition,hour_ha,burned,false_alarm,spark,fire,agricultural,type_cause,relative_humidity,wind_intensity,precipitation,ffmc,dmc,dc,isi,fwi,thc,avg_altitude,avg_inclination,rvdendity,cosn5variety
0,40.330172,-8.222549,2013,Florestal,Coimbra,Penacova,Oliveira do Mondego,2013-03-01 17:54:00,2013-03-01 18:28:59.999998800,0.583333,0.0,0.001,0.0,0.001,0,0.001714,0,0,1,0,0,Intencional,54.0,14.0,0.0,76.300003,2.2,35.200001,1.7,0.7,26.773500,99.8913,17.5053,120.767,22.49
1,40.127576,-8.153059,2013,Florestal,Coimbra,Góis,Góis,2013-04-01 23:56:00,2013-05-01 01:39:59.999998800,697.733333,0.0,0.001,0.0,0.001,0,0.000577,0,0,1,0,0,Negligente,41.0,10.0,0.0,85.400002,2.9,47.400002,3.7,2.6,15.847600,597.4790,49.9571,183.455,21.73
2,40.236057,-7.794691,2013,Florestal,Coimbra,Arganil,Piódão,2013-04-01 13:09:00,2013-04-01 14:30:00.000000000,1.350000,0.0,0.050,0.0,0.050,0,0.037037,0,0,1,0,0,Negligente,51.0,28.0,0.0,81.099998,1.7,25.000000,5.3,3.2,20.834101,748.7660,50.4426,224.046,11.95
3,39.896117,-8.162342,2013,Florestal,Leiria,Pedrógão Grande,Pedrógão Grande,2013-04-01 13:13:00,2013-04-01 13:53:00.000001200,0.666667,0.1,0.100,0.0,0.200,0,0.300000,0,0,1,0,0,Negligente,51.0,28.0,0.0,81.099998,1.7,25.000000,5.3,3.2,20.834101,343.0810,10.0806,138.011,18.89
4,39.549428,-8.768329,2013,Agrícola,Leiria,Porto de Mós,Alvados,2013-04-01 12:00:00,2013-04-01 15:07:59.999998800,3.133333,0.0,0.000,6.5,6.500,0,2.074468,0,0,0,0,1,Negligente,42.0,14.0,0.0,85.800003,4.0,40.200001,4.8,4.1,15.398800,264.8890,11.7616,261.708,15.32

In [117]:
final_dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
lat,142800.0,40.479532,1.213758,0.000000,39.488333,41.033601,41.353437,65.243330
lon,142800.0,-8.283820,0.576866,-51.853745,-8.605477,-8.356951,-7.968331,-0.000000
year,142800.0,2016.745798,2.776449,2013.000000,2015.000000,2017.000000,2019.000000,2022.000000
duration,142800.0,15.291980,106.576422,0.000000,0.450000,0.766667,1.350000,5888.300000
area_populated,142800.0,4.574534,224.481027,0.000000,0.000000,0.000000,0.000000,47215.433221
area_bush,142800.0,3.882413,94.641489,0.000000,0.000000,0.010000,0.129775,13178.860000
area_agricultural,142800.0,0.661383,28.715220,0.000000,0.000000,0.000000,0.000000,5493.424200
area_total,142800.0,9.118330,305.484452,0.000000,0.010000,0.055000,0.500000,53618.811555
reignition,142800.0,0.069825,0.254853,0.000000,0.000000,0.000000,0.000000,1.000000
hour_ha,142800.0,1.074623,21.208895,0.000000,0.018375,0.088889,0.454545,6902.792308
burned,142800.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
false_alarm,142800.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
spark,142800.0,0.652101,0.476305,0.000000,0.000000,1.000000,1.000000,1.000000
fire,142800.0,0.155812,0.362679,0.000000,0.000000,0.000000,0.000000,1.000000
agricultural,142800.0,0.192087,0.393942,0.000000,0.000000,0.000000,0.000000,1.000000
relative_humidity,122921.0,44.724525,17.456145,0.000000,31.000000,43.000000,56.000000,100.499344
wind_intensity,122898.0,10.158956,6.368398,0.000000,5.700000,9.000000,14.000000,90.000000
precipitation,122921.0,0.124756,1.350713,-0.035156,0.000000,0.000000,0.000000,108.000000
ffmc,141286.0,89.222730,71.778751,-80.000000,86.900002,89.755764,92.500000,10071.305664
dmc,141315.0,114.465366,96.874148,-80.000000,37.200001,95.847122,159.000000,1590.033081
dc,141315.0,498.315072,311.542280,-80.000000,228.650002,517.000000,726.799988,6822.709961
isi,141286.0,7.734181,5.297695,-80.000000,4.600000,7.030000,10.100000,192.699997
fwi,141315.0,25.831615,65.032228,-80.000000,13.000000,25.700001,36.299999,20150.089844
thc,93001.0,12.309400,11.165382,0.000000,8.027330,10.830800,13.847000,249.869003
avg_altitude,142747.0,273.912291,242.097593,-63.792500,86.407500,201.484000,399.721000,1813.540000
avg_inclination,142747.0,13.942913,9.434713,0.054086,6.673825,12.006800,19.221700,65.750600
rvdendity,142775.0,344.656296,291.176843,0.000000,149.514000,255.938000,422.590000,2027.110000
cosn5variety,142777.0,17.877137,4.871371,1.000000,14.710000,17.830000,21.040000,39.880000

#### We can't have negative precipitation so we will set the negatives to 0

In [32]:
final_dataset['precipitation'] = np.where(final_dataset['precipitation'] < 0, 0, final_dataset['precipitation'])

#### Adding the CO2 expelled to the atmosphere for each fire

In [33]:
final_dataset['co2_generated'] = (final_dataset['area_populated']*1.28+final_dataset['area_bush']*14+final_dataset['area_agricultural']*1.28)*1.7264

### Making some typing corrections to district, county and parish columns so the data is all unified.

I noted before that some locals have upper and downcase issues, I'll address them now

In [34]:
for element in ['district', 'county', 'parish']:
    final_dataset[element] = final_dataset[element].str.replace(" Da ",' da ')
    final_dataset[element] = final_dataset[element].str.replace(" De ",' de ')
    final_dataset[element] = final_dataset[element].str.replace(" Do ",' do ')

### Checking for final Nans

In [35]:
final_dataset.isna().sum()

lat                      0
lon                      0
year                     0
type                     0
district                 0
county                   0
parish                   0
alert_date               0
extinction_date          0
duration                 0
area_populated           0
area_bush                0
area_agricultural        0
area_total               0
reignition               0
hour_ha                  0
burned                   0
false_alarm              0
spark                    0
fire                     0
agricultural             0
type_cause           23177
relative_humidity    19879
wind_intensity       19902
precipitation        19879
ffmc                  1514
dmc                   1485
dc                    1485
isi                   1514
fwi                   1485
thc                  49799
avg_altitude            53
avg_inclination         53
rvdendity               25
cosn5variety            23
co2_generated            0
dtype: int64

In [36]:
# I have no option than dropping the column thc and the rows were relative humidity, wind intensity and precipitation are null 
# because for the model i want to build this is essencial info.
final_dataset = final_dataset.dropna(subset=['relative_humidity', 'hour_ha', 'avg_altitude'])
final_dataset = final_dataset.drop(['thc'], axis=1)

# Droping a few more invalid rows
final_dataset = final_dataset[~final_dataset['isi'].isna()]
final_dataset = final_dataset[~final_dataset['wind_intensity'].isna()]

#### I will assign every null of type_cause to unknown because they are in fact, unknown and translate every value to an english translated one for better understanding.

In [37]:
final_dataset['type_cause'][final_dataset['type_cause'].isna()] = 'Desconhecida'
final_dataset['type_cause'] = final_dataset['type_cause'].map({"Desconhecida" : 'Unknown', "Negligente" : 'Negligence', "Intencional" : 'Intentional', "Reacendimento" : 'Re-ignition', 'Natural' : 'Natural'})   
final_dataset['type_cause'].value_counts()

Unknown        57593
Negligence     35030
Intentional    20061
Re-ignition     9185
Natural          951
Name: type_cause, dtype: int64

In [38]:
final_dataset['type_cause'].isna().sum()

0

In [40]:
final_dataset.head(2)

,lat,lon,year,type,district,county,parish,alert_date,extinction_date,duration,area_populated,area_bush,area_agricultural,area_total,reignition,hour_ha,burned,false_alarm,spark,fire,agricultural,type_cause,relative_humidity,wind_intensity,precipitation,ffmc,dmc,dc,isi,fwi,avg_altitude,avg_inclination,rvdendity,cosn5variety,co2_generated
0,40.330172,-8.222549,2013,Florestal,Coimbra,Penacova,Oliveira do Mondego,2013-03-01 17:54:00,2013-03-01 18:28:59.999998800,0.583333,0.0,0.001,0.0,0.001,0,0.001714,0,0,1,0,0,Intentional,54.0,14.0,0.0,76.300003,2.2,35.200001,1.7,0.7,99.8913,17.5053,120.767,22.49,0.02417
1,40.127576,-8.153059,2013,Florestal,Coimbra,Góis,Góis,2013-04-01 23:56:00,2013-05-01 01:39:59.999998800,697.733333,0.0,0.001,0.0,0.001,0,0.000577,0,0,1,0,0,Negligence,41.0,10.0,0.0,85.400002,2.9,47.400002,3.7,2.6,597.4790,49.9571,183.455,21.73,0.02417

In [41]:
final_dataset['parish'][final_dataset['district']=='Viana do Castelo'].value_counts()

Gandra                           152
Lavradas                         132
Portela                          125
Refóios do Lima                  118
Carvoeiro                        110
                                ...
Caminha                            1
Arcos de Valdevez (são Paio)       1
Padreiro (salvador)                1
Arga de Cima                       1
Viana do Castelo (Monserrate)      1
Name: parish, Length: 310, dtype: int64

#### The parish's inside brackets are essencially lke north and south of the same place so I will remove all brackets and everything inside them effectivly grouping the fires of this small sub-parish's

In [42]:
words = list(final_dataset['parish'][final_dataset['parish'].str.contains("\(.*?\)")].unique())
file_lst_trimmed = [re.sub(r' \(.*?\)', '', file) for file in words]

final_dataset[final_dataset['parish'].isin(file_lst_trimmed)]
final_dataset['parish'] = [re.sub(r' \(.*?\)', '', file) for file in final_dataset['parish']]

### Exporting the new trimmed and treated dataset to csv and our MySQL database for later access and use

In [46]:
final_dataset.to_csv('Full fires 2013-2022 with weather to model.csv')

In [47]:
import getpass
from sqlalchemy import create_engine

password = getpass.getpass()

········

In [48]:
connection_string = 'mysql+pymysql://root:' + password + '@localhost/fire_db'
engine = create_engine(connection_string)

final_dataset.to_sql('fires_clean',con=engine,index=False,if_exists='replace')

122820